import type { Metadata } from "next";
import { Inter, Oregano } from "next/font/google";
import "./globals.css";
import { cn } from "@/ui/cn";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "700", "800"],
});

const oregano = Oregano({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: { colorPrimary: "#000000" },
        elements: {
          avatarBox: "w-6 h-6",
        },
      }}
    >
      <html
        lang="en"
        className="bg-background text-foreground dark:bg-foreground dark:text-background antialiased"
      >
        <body
          className={cn(
            inter.variable,
            oregano.variable,
            "grid grid-rows-[auto_minmax(0,1fr)_auto] min-h-[100dvh]"
          )}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
