name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install && bunx playwright install --with-deps
      - name: Run tests
        run: bun run e2e:ci
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
