name: PR Checks

on:
  pull_request:

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Run formatter check
        run: bun run format:ci

      - name: Run db:codegen
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
        run: bun run db:codegen

      - name: Run type check
        run: bun run check

      - name: Run tests
        run: bun test
